# application.yaml
server:
  port: 28080

spring:
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true


  datasource:
    url: jdbc:mysql://localhost:3306/baihe_wbq?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: woainiaiwo121

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.model

